version: '3'

services:
  bearerbox:
    container_name: bearerbox
    hostname: bearerbox
    image: ghcr.io/gpproton/kannel:1.4.5-9
    privileged: true
    restart: unless-stopped
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf
    ports:
      - 13000:13000
      - 13013:13013
  smsbox:
    container_name: smsbox
    hostname: smsbox
    image: ghcr.io/gpproton/kannel:1.4.5-9
    restart: unless-stopped
    entrypoint:
      - /usr/sbin/smsbox
      - /etc/kannel/kannel.conf
    ports:
      - 13001:13001
      - 13131:13131
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf

  playsms:
    container_name: playsms
    hostname: playsms
    image: playsms/playsms:1.4.5
    restart: unless-stopped
    ports:
      - 8080:80
      - 2222:22
    volumes:
    - "$STORE_ROOT/playsms:/var/lib/mysql"
