version: '3'

services:
  bearerbox:
    container_name: bearerbox
    hostname: bearerbox
    image: ghcr.io/gpproton/kannel:${VERSION}
    build:
      context: ./kannel
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf
    ports:
      - 13000:13000
      - 13013:13013

  smsbox:
    container_name: smsbox
    hostname: smsbox
    image: ghcr.io/gpproton/kannel:${VERSION}
    build:
      context: ./kannel
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint:
      - /usr/sbin/smsbox
      - /etc/kannel/kannel.conf
    ports:
      - 13001:13001
      - 13131:13131
    volumes:
      - ./kannel.conf:/etc/kannel/kannel.conf
